import { Injectable, signal } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class TranslateService {
  private lang = signal<'fr' | 'en'>('fr');

  private translations: Record<string, Record<string, string>> = {
    fr: {
      panier: 'Ajouter au panier',
      payer: 'Payer',
      vider: 'Vider le panier',
      bienvenu: 'Bienvenue',
      championnats: 'Choisissez un championnat',
      clubs: 'Choisissez une équipe',
      mon_panier: 'Votre Panier',
      panier_vide: 'Votre panier est vide',
      connexion: 'Connexion',
      mail: 'Email',
      password: 'Mot de passe',
      register: 'Inscription',
      name: 'Nom',
      firstname: 'Prénom',
      confirm: 'Confirmer',
      createaccount: 'Créer un compte',
      users: 'Utilisateurs',
      jerseys: 'Maillots',
      role: 'Rôle',
      action: 'Action',
      delete: 'Supprimer',
      protected_admin: 'Admin protégé',
      team: 'Équipe',
      type: 'Type',
      price: 'Prix',
      stock: 'Stock',
      no_jerseys: 'Aucun maillot trouvé',
      interface_admin: 'Interface administrateur',
      domicile: 'Domicile',
      exterieur: 'Extérieur',
      third: 'Third',
      size: 'Taille',
      inStock: 'En stock',
      outofstock: 'Rupture de stock',
      admin_cant_pay: 'Les administrateurs ne peuvent pas ajouter au panier.',
      reduction: 'Réduction',
      modify: 'Modifier',
      addjersey: 'Ajouter un maillot',
      add: 'Ajouter',
      championship: 'Championnats',
      image: 'Image',
      unblock: 'Débloquer',
      block: 'Bloquer',
      cancel: 'Annuler',
      save: 'Enregistrer',
      are_you_sure: 'Vous êtes sur ?',
      jersey_added: 'Le maillot a bien été ajouté !',
      jersey_updated: 'Le maillot a été mis à jour !',
      payment: 'Paiement',
      card_number: 'Numéro de carte',
      command: 'Commander',
      command_inprogress: 'Commande en cours ...',
      resume: 'Résumé',
      pay_done: 'Paiement réussi !',
      thank_for_pay: 'Merci pour votre achat !',
    },
    en: {
      panier: 'Add to Cart',
      payer: 'Pay',
      vider: 'Empty cart',
      bienvenu: 'Welcome',
      championnats: 'Choose a championship',
      clubs: 'Choose a team',
      mon_panier: 'Your cart',
      panier_vide: 'Your cart is empty',
      connexion: 'Login',
      mail: 'Email',
      password: 'Password',
      register: 'Register',
      name: 'Name',
      firstname: 'Firstname',
      welcome: 'Welcome',
      confirm: 'Confirm',
      createaccount: 'Create an account',
      users: 'Users',
      jerseys: 'Jerseys',
      role: 'Role',
      action: 'Action',
      delete: 'Delete',
      protected_admin: 'Protected Admin',
      team: 'Team',
      type: 'Like',
      price: 'Price',
      stock: 'Stock',
      no_jerseys: 'No Jerseys Found',
      interface_admin: 'Administrator Interface',
      domicile: 'Home',
      exterieur: 'Away',
      third: 'Third',
      size: 'Size',
      inStock: 'In stock',
      outofstock: 'Out of stock',
      admin_cant_pay: 'Admins cannot add to cart.',
      reduction: 'Reduction',
      modify: 'Modify',
      addjersey: 'Add a jersey',
      add: 'Add',
      championship: 'Championship',
      image: 'Image',
      unblock: 'Unblock',
      block: 'To block',
      cancel: 'Cancel',
      save: 'Save',
      are_you_sure: 'Are you sure ?',
      jersey_added: 'The jersey has been added !',
      jersey_updated: 'The jersey has been updated !',
      payment: 'Payment',
      card_number: 'Card number',
      command: 'To command',
      command_inprogress: 'Command in progress ...',
      resume: 'Resume',
      pay_done: 'Payment done !',
      thank_for_pay: 'Thank you for your purshase !',
    },
  };

  translate(key: string): string {
    const currentLang = this.lang();
    return this.translations[currentLang][key] || key;
  }

  setLang(lang: 'fr' | 'en') {
    this.lang.set(lang);
  }

  getLang() {
    return this.lang();
  }
}
